SIMULATION_MODE = False
DEBUG_MODE = True

MIN_V = 45
MAX_V = 255

MORPHOLOGICAL_OPERATIONS_ON = True
KERNEL_SHAPE = (4, 4)

POLY_DEGREE = 2

# Configuracion de la comunicacion UDP
UDP_IP_wemos = "192.168.0.109"
UDP_PORT_wemos = 1234
UDP_PORT_rpi = 1233
UDP_IP_mando = ""

CAMERA_WIDTH = 320
CAMERA_HEIGHT = 240

Y_THRESHOLD = CAMERA_HEIGHT // 3
MIN_LINE_LENGTH_PERCENTAGE = 0.4

LOOP_FREQ = 50

MIN_SPEED_FORWARD = 30
MIN_SPEED_TURN = 45

MAX_REGION_AREA = 8000
MIN_REGION_AREA = 400
# ASPECT_RATIO = 0.05
